### PR TITLE
Swift 3 Compatible

### PR DESCRIPTION
**Pull request by Sadmansamee**

### CODE REVIEW

**Comment by Sadmansamee** [comment]
@andrealufino  so is it going to be merged?

**Comment by andrealufino** [comment]
I don't have write access for the repo

**Comment by johnyboy6000** [comment]
When is this likely to be merged, I rely on it on a current project that needs updating.

**Comment by evnaz** [comment]
Sorry guys for the huge delay. 
@Sadmansamee Thanks for the great work!

**Comment by Sadmansamee** [comment]
@evnaz Appreciate your work man.

**Pull request merged**
